# Generated by Django 4.2.4 on 2024-11-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
